'((:number-of-objects . 10) (:categorization-mode . :shared-individual-objects)
  (:utterance-type . :single-word) (:meaning-type . :single-category)
  (:world-type . :individual-objects) (:update-category-scores)
  (:probability-for-word-invention . 1.0)
  (:use-meaning-score-as-initial-word-score)
  (:conceptualization-result-mode . :all) (:adopted-meanings-in-repair . :all)
  (:initial-word-score . 0.5) (:rate-task-mode . :multiply)
  (succeeded-task-upperbound . -1) (:population-size . 10)
  (experiment-class . ng) (:word-score-delta-success . 0.1)
  (:word-score-delta-fail . -0.1) (:word-score-delta-inhibit . 0.0)
  (:word-score-constant-decay-factor . -0.05))